name: Versioning

on:
  push:
    branches: [ main ]

jobs:
  versioning:
      if: "!contains(github.event.head_commit.message, 'Auto update version')"
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Update version
        id: new-version
        run: python .github/workflows/update_version.py
      - name: Auto update version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "AttackingOrDefending"
          git remote set-url origin ${{ secrets.ssh }}
          git add versioning.yml
          git commit -m "Auto update version to ${{ steps.new-version.outputs.new_version }}"
          git push origin HEAD:main
