name: Versioning

on:
  push:
    branches: [ main ]

jobs:
  versioning:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Update version
        run: python .github/workflows/update_version.py
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add versioning.yml
      - name: commit changed files
        run: git commit -m "Auto updating version"
      - name: fetch from master
        run: git fetch origin main
      - name: push code to master
        run: git push origin HEAD:main
