name: Versioning

on:
  push:
    branches: [ main ]

jobs:
  versioning:
      if: "!contains(github.event.head_commit.message, 'Auto updating version')"
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.11 ${{ github.event.head_commit.message }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Update version
        run: python .github/workflows/update_version.py
      - name: switching from HTTPS to SSH
        run: |
          git remote set-url origin ${{ secrets.ssh }}
          git status
          git add versioning.yml
          git config --global user.email "40605232+AttackingOrDefending@users.noreply.github.com"
          git config --global user.name "AttackingOrDefending"
          git commit -m "Auto updating version"
          git fetch origin main
          git push origin HEAD:main
