name: Versioning

on:
  push:
    branches: [ main ]

jobs:
  versioning:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Update version
        run: python .github/workflows/update_version.py
      - name: Push changes
        run: |
          git remote set-url origin https://${{ secrets.token }}@github.com/AttackingOrDefending/github-actions-versioning
          git config --global user.email "40605232+AttackingOrDefending@users.noreply.github.com"
          git config --global user.name "AttackingOrDefending"
          git add versioning.yml
          git commit -m "Update version"
          git fetch origin main
          git push origin HEAD:main
