name: Versioning

on:
  push:
    branches: [ main ]

jobs:
  versioning:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Update version
        run: python .github/workflows/update_version.py
      - name: Push changes
        uses: pre-commit/action@v3.0.0
